"""add database constraints defaults and index cleanup

Revision ID: 057e1ffeec3c
Revises: 0c9723753bb9
Create Date: 2026-08-06 15:56:02.208445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '057e1ffeec3c'
down_revision: Union[str, Sequence[str], None] = '0c9723753bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default='aberto',
               nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.create_check_constraint('ck_accounts_cliente_min_length', 'accounts', 'char_length(btrim(cliente)) >= 2')
    op.create_check_constraint('ck_accounts_status_valid', 'accounts', "status IN ('aberto', 'atrasado', 'pago')")
    op.create_check_constraint('ck_accounts_valor_positive', 'accounts', 'valor > 0')
    op.alter_column('knowledge', 'knowledge_type',
               existing_type=sa.VARCHAR(length=50),
               server_default='insight',
               existing_nullable=False)
    op.alter_column('knowledge', 'severity',
               existing_type=sa.VARCHAR(length=30),
               server_default='info',
               existing_nullable=False)
    op.alter_column('knowledge', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_knowledge_id'), table_name='knowledge')
    op.create_check_constraint('ck_knowledge_agent_name_min_length', 'knowledge', 'char_length(btrim(agent_name)) >= 2')
    op.create_check_constraint('ck_knowledge_event_name_min_length', 'knowledge', 'char_length(btrim(event_name)) >= 2')
    op.create_check_constraint('ck_knowledge_message_min_length', 'knowledge', 'char_length(btrim(message)) >= 2')
    op.create_check_constraint('ck_knowledge_severity_valid', 'knowledge', "severity IN ('critical', 'high', 'medium', 'info')")
    op.create_check_constraint('ck_knowledge_title_min_length', 'knowledge', 'char_length(btrim(title)) >= 2')
    op.create_check_constraint('ck_knowledge_type_min_length', 'knowledge', 'char_length(btrim(knowledge_type)) >= 2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_knowledge_type_min_length', 'knowledge', type_='check')
    op.drop_constraint('ck_knowledge_title_min_length', 'knowledge', type_='check')
    op.drop_constraint('ck_knowledge_severity_valid', 'knowledge', type_='check')
    op.drop_constraint('ck_knowledge_message_min_length', 'knowledge', type_='check')
    op.drop_constraint('ck_knowledge_event_name_min_length', 'knowledge', type_='check')
    op.drop_constraint('ck_knowledge_agent_name_min_length', 'knowledge', type_='check')
    op.create_index(op.f('ix_knowledge_id'), 'knowledge', ['id'], unique=False)
    op.alter_column('knowledge', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge', 'severity',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge', 'knowledge_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('ck_accounts_valor_positive', 'accounts', type_='check')
    op.drop_constraint('ck_accounts_status_valid', 'accounts', type_='check')
    op.drop_constraint('ck_accounts_cliente_min_length', 'accounts', type_='check')
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
