"""create initial schema

Revision ID: 558931d55c94
Revises: 
Create Date: 2026-08-05 12:28:30.407345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558931d55c94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('knowledge_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_account_id'), 'knowledge', ['account_id'], unique=False)
    op.create_index(op.f('ix_knowledge_agent_name'), 'knowledge', ['agent_name'], unique=False)
    op.create_index(op.f('ix_knowledge_event_name'), 'knowledge', ['event_name'], unique=False)
    op.create_index(op.f('ix_knowledge_id'), 'knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_knowledge_type'), 'knowledge', ['knowledge_type'], unique=False)
    op.create_index(op.f('ix_knowledge_resolved'), 'knowledge', ['resolved'], unique=False)
    op.create_index(op.f('ix_knowledge_severity'), 'knowledge', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_severity'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_resolved'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_type'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_id'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_event_name'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_agent_name'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_account_id'), table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
