"""add memory system

Revision ID: ed6fc40a90a4
Revises: 8b0c5f3e2a19
Create Date: 2026-08-11 14:26:14.364649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed6fc40a90a4'
down_revision: Union[str, Sequence[str], None] = '8b0c5f3e2a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=True),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('subject_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Numeric(precision=4, scale=3), server_default='0.500', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('supersedes_memory_id', sa.BigInteger(), nullable=True),
    sa.Column('context_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope_type = 'global' AND account_id IS NULL AND subject_user_id IS NULL) OR (scope_type = 'account' AND account_id IS NOT NULL AND subject_user_id IS NULL) OR (scope_type = 'user' AND account_id IS NULL AND subject_user_id IS NOT NULL)", name='ck_memory_items_scope_integrity'),
    sa.CheckConstraint("memory_type IN ('fact', 'event', 'observation', 'decision', 'summary')", name='ck_memory_items_memory_type_valid'),
    sa.CheckConstraint("scope_type IN ('global', 'account', 'user')", name='ck_memory_items_scope_type_valid'),
    sa.CheckConstraint("source_type IN ('database', 'upload', 'user', 'agent', 'system', 'api', 'derived')", name='ck_memory_items_source_type_valid'),
    sa.CheckConstraint("status IN ('active', 'superseded', 'expired', 'invalidated', 'archived')", name='ck_memory_items_status_valid'),
    sa.CheckConstraint("status NOT IN ('superseded', 'invalidated') OR (status_reason IS NOT NULL AND char_length(btrim(status_reason)) >= 1)", name='ck_memory_items_status_reason_required'),
    sa.CheckConstraint('char_length(btrim(content)) >= 1', name='ck_memory_items_content_not_blank'),
    sa.CheckConstraint('char_length(btrim(source_reference)) >= 1', name='ck_memory_items_source_reference_not_blank'),
    sa.CheckConstraint('char_length(btrim(title)) >= 1', name='ck_memory_items_title_not_blank'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_memory_items_confidence_range'),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name='ck_memory_items_importance_range'),
    sa.CheckConstraint('supersedes_memory_id IS NULL OR supersedes_memory_id <> id', name='ck_memory_items_not_self_superseding'),
    sa.CheckConstraint('valid_until IS NULL OR valid_until > valid_from', name='ck_memory_items_valid_time_range'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_memory_items_account_id_accounts', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_memory_items_created_by_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], name='fk_memory_items_subject_user_id_users', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_memory_id'], ['memory_items.id'], name='fk_memory_items_supersedes_memory_id_memory_items', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_items_account_status_type_valid_from', 'memory_items', ['account_id', 'status', 'memory_type', 'valid_from'], unique=False)
    op.create_index('ix_memory_items_active_valid_until', 'memory_items', ['valid_until'], unique=False, postgresql_where=sa.text("status = 'active' AND valid_until IS NOT NULL"), sqlite_where=sa.text("status = 'active' AND valid_until IS NOT NULL"))
    op.create_index('ix_memory_items_source_type_reference', 'memory_items', ['source_type', 'source_reference'], unique=False)
    op.create_index('ix_memory_items_status_type_created_at', 'memory_items', ['status', 'memory_type', 'created_at'], unique=False)
    op.create_index('ix_memory_items_user_status_type_valid_from', 'memory_items', ['subject_user_id', 'status', 'memory_type', 'valid_from'], unique=False)
    op.create_index('uq_memory_items_active_account_key', 'memory_items', ['account_id', 'memory_key'], unique=True, postgresql_where=sa.text("scope_type = 'account' AND status = 'active' AND memory_key IS NOT NULL"), sqlite_where=sa.text("scope_type = 'account' AND status = 'active' AND memory_key IS NOT NULL"))
    op.create_index('uq_memory_items_active_global_key', 'memory_items', ['memory_key'], unique=True, postgresql_where=sa.text("scope_type = 'global' AND status = 'active' AND memory_key IS NOT NULL"), sqlite_where=sa.text("scope_type = 'global' AND status = 'active' AND memory_key IS NOT NULL"))
    op.create_index('uq_memory_items_active_user_key', 'memory_items', ['subject_user_id', 'memory_key'], unique=True, postgresql_where=sa.text("scope_type = 'user' AND status = 'active' AND memory_key IS NOT NULL"), sqlite_where=sa.text("scope_type = 'user' AND status = 'active' AND memory_key IS NOT NULL"))
    op.create_table('memory_evidence',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('memory_id', sa.BigInteger(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('source_memory_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), server_default='1.000', nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('context_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation IN ('supports', 'contradicts', 'context')", name='ck_memory_evidence_relation_valid'),
    sa.CheckConstraint("source_type IN ('database', 'upload', 'user', 'agent', 'system', 'api', 'derived')", name='ck_memory_evidence_source_type_valid'),
    sa.CheckConstraint('char_length(btrim(evidence_text)) >= 1', name='ck_memory_evidence_text_not_blank'),
    sa.CheckConstraint('char_length(btrim(source_reference)) >= 1', name='ck_memory_evidence_source_reference_not_blank'),
    sa.CheckConstraint('char_length(evidence_hash) = 64', name='ck_memory_evidence_hash_length'),
    sa.CheckConstraint('source_memory_id IS NULL OR source_memory_id <> memory_id', name='ck_memory_evidence_not_self_reference'),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='ck_memory_evidence_weight_range'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_memory_evidence_created_by_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_items.id'], name='fk_memory_evidence_memory_id_memory_items', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_memory_id'], ['memory_items.id'], name='fk_memory_evidence_source_memory_id_memory_items', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'evidence_hash', name='uq_memory_evidence_memory_hash')
    )
    op.create_index('ix_memory_evidence_memory_created_at', 'memory_evidence', ['memory_id', 'created_at'], unique=False)
    op.create_index('ix_memory_evidence_source_memory_id', 'memory_evidence', ['source_memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_evidence_source_memory_id', table_name='memory_evidence')
    op.drop_index('ix_memory_evidence_memory_created_at', table_name='memory_evidence')
    op.drop_table('memory_evidence')
    op.drop_index('uq_memory_items_active_user_key', table_name='memory_items', postgresql_where=sa.text("scope_type = 'user' AND status = 'active' AND memory_key IS NOT NULL"), sqlite_where=sa.text("scope_type = 'user' AND status = 'active' AND memory_key IS NOT NULL"))
    op.drop_index('uq_memory_items_active_global_key', table_name='memory_items', postgresql_where=sa.text("scope_type = 'global' AND status = 'active' AND memory_key IS NOT NULL"), sqlite_where=sa.text("scope_type = 'global' AND status = 'active' AND memory_key IS NOT NULL"))
    op.drop_index('uq_memory_items_active_account_key', table_name='memory_items', postgresql_where=sa.text("scope_type = 'account' AND status = 'active' AND memory_key IS NOT NULL"), sqlite_where=sa.text("scope_type = 'account' AND status = 'active' AND memory_key IS NOT NULL"))
    op.drop_index('ix_memory_items_user_status_type_valid_from', table_name='memory_items')
    op.drop_index('ix_memory_items_status_type_created_at', table_name='memory_items')
    op.drop_index('ix_memory_items_source_type_reference', table_name='memory_items')
    op.drop_index('ix_memory_items_active_valid_until', table_name='memory_items', postgresql_where=sa.text("status = 'active' AND valid_until IS NOT NULL"), sqlite_where=sa.text("status = 'active' AND valid_until IS NOT NULL"))
    op.drop_index('ix_memory_items_account_status_type_valid_from', table_name='memory_items')
    op.drop_table('memory_items')
    # ### end Alembic commands ###
