from typing import Literal


UserRole = Literal[
    "viewer",
    "analyst",
    "manager",
    "executive",
    "administrator",
    "developer",
]

Permission = Literal[
    "dashboard.view",
    "clients.view",
    "clients.manage",
    "imports.execute",
    "executive.view",
    "brain.view",
    "administration.ai-operations",
    "developer.ui-showcase",
    "memory:read",
    "memory:create",
    "memory:evidence",
    "memory:supersede",
    "memory:invalidate",
    "memory:archive",
    "memory:history",
    "memory:read_user_scope",
    "memory:read_global",
    "memory:manage_global",
    "work:read",
    "work:create",
    "work:update",
    "work:comment",
    "work:manage_dependencies",
    "work:manage_recurrence",
    "work:assign",
    "work:read_user_scope",
    "work:manage_user_scope",
    "work:read_global",
    "work:manage_global",
    "skill:execute",
    "skill:execute_mutating",
    "skill:execute_external",
    "skill:execute_user_scope",
]

USER_ROLES: tuple[UserRole, ...] = (
    "viewer",
    "analyst",
    "manager",
    "executive",
    "administrator",
    "developer",
)

ROLE_PERMISSIONS: dict[
    UserRole,
    frozenset[Permission],
] = {
    "viewer": frozenset({
        "dashboard.view",
        "clients.view",
        "memory:read",
        "work:read",
    }),
    "analyst": frozenset({
        "dashboard.view",
        "clients.view",
        "clients.manage",
        "imports.execute",
        "brain.view",
        "memory:read",
        "memory:create",
        "memory:evidence",
        "memory:history",
        "work:read",
        "work:create",
        "work:update",
        "work:comment",
        "skill:execute",
    }),
    "manager": frozenset({
        "dashboard.view",
        "clients.view",
        "clients.manage",
        "imports.execute",
        "brain.view",
        "executive.view",
        "memory:read",
        "memory:create",
        "memory:evidence",
        "memory:supersede",
        "memory:invalidate",
        "memory:archive",
        "memory:history",
        "work:read",
        "work:create",
        "work:update",
        "work:comment",
        "work:manage_dependencies",
        "work:manage_recurrence",
        "work:assign",
        "skill:execute",
        "skill:execute_mutating",
    }),
    "executive": frozenset({
        "dashboard.view",
        "clients.view",
        "clients.manage",
        "imports.execute",
        "brain.view",
        "executive.view",
        "memory:read",
        "memory:create",
        "memory:evidence",
        "memory:supersede",
        "memory:invalidate",
        "memory:archive",
        "memory:history",
        "work:read",
        "work:create",
        "work:update",
        "work:comment",
        "work:manage_dependencies",
        "work:manage_recurrence",
        "work:assign",
        "skill:execute",
        "skill:execute_mutating",
    }),
    "administrator": frozenset({
        "dashboard.view",
        "clients.view",
        "clients.manage",
        "imports.execute",
        "brain.view",
        "executive.view",
        "administration.ai-operations",
        "memory:read",
        "memory:create",
        "memory:evidence",
        "memory:supersede",
        "memory:invalidate",
        "memory:archive",
        "memory:history",
        "memory:read_user_scope",
        "memory:read_global",
        "memory:manage_global",
        "work:read",
        "work:create",
        "work:update",
        "work:comment",
        "work:manage_dependencies",
        "work:manage_recurrence",
        "work:assign",
        "work:read_user_scope",
        "work:manage_user_scope",
        "work:read_global",
        "work:manage_global",
        "skill:execute",
        "skill:execute_mutating",
        "skill:execute_external",
        "skill:execute_user_scope",
    }),
    "developer": frozenset({
        "dashboard.view",
        "clients.view",
        "clients.manage",
        "imports.execute",
        "brain.view",
        "executive.view",
        "administration.ai-operations",
        "developer.ui-showcase",
        "memory:read",
        "memory:create",
        "memory:evidence",
        "memory:supersede",
        "memory:invalidate",
        "memory:archive",
        "memory:history",
        "memory:read_user_scope",
        "memory:read_global",
        "memory:manage_global",
        "work:read",
        "work:create",
        "work:update",
        "work:comment",
        "work:manage_dependencies",
        "work:manage_recurrence",
        "work:assign",
        "work:read_user_scope",
        "work:manage_user_scope",
        "work:read_global",
        "work:manage_global",
        "skill:execute",
        "skill:execute_mutating",
        "skill:execute_external",
        "skill:execute_user_scope",
    }),
}


def has_permission(
    role: str,
    permission: Permission,
) -> bool:
    if role not in ROLE_PERMISSIONS:
        return False

    return permission in ROLE_PERMISSIONS[
        role  # type: ignore[index]
    ]
